VERSION 0.7
IMPORT ../.. AS base

build:
  ARG --required VERSION
  ARG --required PAYLOAD_ADDRESS
  FROM base+pnpm
  DO base+INSTALLPRUNED --fromtarget="pruned-web"

  ENV NEXT_TELEMETRY_DISABLED 1
  ENV PAYLOAD_ADDRESS "$PAYLOAD_ADDRESS"
  WORKDIR /app/apps/web
  RUN ./update.version.sh "$VERSION"
  RUN pnpm build
  SAVE ARTIFACT .next/standalone
  SAVE ARTIFACT .next/static
  SAVE ARTIFACT public

run:
  ARG --required PAYLOAD_ADDRESS
  FROM base+node
  LABEL org.opencontainers.image.source="https://github.com/kian8017/indexingbrain"
  WORKDIR /app

  RUN addgroup --system --gid 1001 nodejs
  RUN adduser --system --uid 1001 nextjs
  USER nextjs

  COPY --chown=nextjs:nodejs (+build/standalone --PAYLOAD_ADDRESS="$PAYLOAD_ADDRESS") ./
  COPY --chown=nextjs:nodejs --dir (+build/static --PAYLOAD_ADDRESS="$PAYLOAD_ADDRESS") ./apps/web/.next/static
  COPY --chown=nextjs:nodejs --dir (+build/public --PAYLOAD_ADDRESS="$PAYLOAD_ADDRESS") ./apps/web/public

  ENV NEXT_TELEMETRY_DISABLED 1
  ENV PAYLOAD_ADDRESS "$PAYLOAD_ADDRESS"
  ENV HOSTNAME "0.0.0.0"

  EXPOSE 3000
  CMD ["node", "apps/web/server.js"]
  SAVE IMAGE ib-web

publish:
  ARG --required VERSION
  ARG --required PAYLOAD_ADDRESS
  ARG BASE = "ghcr.io/kian8017/ib-web"
  FROM +run
  SAVE IMAGE --push "$BASE:latest" "$BASE:$VERSION"
