# used to bring up services for testing
version: "3.8"
services:
  cms:
    image: "seeded-cms"
    ports:
      - "3000:3000"
    environment:
      - "PAYLOAD_SECRET=testing"
      - "MONGODB_URI=mongodb://mongodb/ib"

  mongodb:
    image: "seeded-db"
    ports:
      - "27017:27017"
    volumes:
      - "test-ib-cms:/data/db"

volumes:
  test-ib-cms:
