version: "3.8"
services:
  ibdev:
    image: "ibdev"
    volumes:
      - "../..:/indexingbrain"
      - "$SSH_AUTH_SOCK:/sshagent"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "SSH_AUTH_SOCK=/sshagent"
    tty: true
    stdin_open: true
