VERSION 0.7

#COPY gitconfig /root/.gitconfig

dev:
  # change to 22.04
  FROM node:20.5.1
  # combine update with install
  RUN apt-get update
  RUN apt-get install -y git ssh curl file vim
  RUN npm install -g pnpm turbo

  RUN curl -fsSL https://get.docker.com |bash

  RUN wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly

  CMD [ "sleep", "86400" ]
  SAVE IMAGE ibdev

up:
  LOCALLY
  RUN docker compose up -d

down:
  LOCALLY
  RUN docker compose down
