version: "3.8"
services:
  traefik:
    image: "traefik:v2.10"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  web:
    image: "ghcr.io/kian8017/ib-web:latest"

  cms:
    image: "ghcr.io/kian8017/ib-cms:latest"

  mongodb:
    image: "mongo:latest"
