version: "3.8"
services:
  traefik:
    command:
      - "--log"
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=kianmusser@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      - "--entrypoints.http.http.redirections.entryPoint.permanent=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/ib_vol/traefik:/letsencrypt
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.dummyservice.loadbalancer.server.port=2222"
      placement:
        constraints:
          - node.role == manager

  web:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web-router.rule=Host(`indexing-brain.org`)"
        - "traefik.http.routers.web-router.entrypoints=https"
        - "traefik.http.routers.web-router.tls.certresolver=myresolver"
        - "traefik.http.services.web-service.loadbalancer.server.port=3000"
    environment:
      - "PAYLOAD_ADDRESS=https://admin.indexing-brain.org"

  cms:
    environment:
      - "PAYLOAD_SECRET=production-payload-secret"
      - "MONGODB_URI=mongodb://mongodb/ib"

    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cms-router.rule=Host(`admin.indexing-brain.org`)"
        - "traefik.http.routers.cms-router.tls.certresolver=myresolver"
        - "traefik.http.services.cms-service.loadbalancer.server.port=3000"

  mongodb:
    volumes:
      - "/mnt/ib_vol/mongodb:/data/db"
