---
- name: Configure Indexing-Brain server
  hosts: server
  remote_user: root
  vars:
    ubuntu_release: jammy
    ansible_host_key_checking: false

  tasks:
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: true

    - name: Install packages required for docker
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - python3-pip
          - virtualenv
          - python3-setuptools

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ubuntu_release }} stable"
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Install docker python packages for use by Ansible
      ansible.builtin.pip:
        name:
          - docker
          - jsondiff
          - pyyaml

    - name: Check if reboot needed
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists

    - name: ufw - Allow SSH
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: ufw - Allow http
      community.general.ufw:
        rule: allow
        port: 80

    - name: ufw - Allow https
      community.general.ufw:
        rule: allow
        port: 443

    - name: ufw - enable
      community.general.ufw:
        state: enabled
