---
- name: Deploy Docker
  hosts: server
  remote_user: root
  vars:
    ansible_host_key_checking: false

  tasks:
    - name: Ensure docker is running in swarm mode
      community.docker.docker_swarm:
        state: present
        advertise_addr: 127.0.0.1

    - name: copy over docker stack template
      ansible.builtin.copy:
        src: ../docker/docker-stack.yml
        dest: /opt/docker-stack.yml

    - name: Deploy docker stack
      community.docker.docker_stack:
        state: present
        name: ib
        prune: true
        compose:
          - /opt/docker-stack.yml
