---
- name: Deploy Docker
  hosts: server
  remote_user: root
  vars:
    ansible_host_key_checking: false

  tasks:
    - name: Ensure docker is running in swarm mode
      community.docker.docker_swarm:
        state: present
        advertise_addr: 127.0.0.1

    - name: Copy over docker compose files
      ansible.builtin.copy:
        src: ../docker/{{ item }}
        dest: /opt/{{ item }}
      loop:
        - compose.yml
        - compose.prod.yml

    - name: Deploy docker stack
      community.docker.docker_stack:
        state: present
        name: ib
        prune: true
        compose:
          - /opt/compose.yml
          - /opt/compose.prod.yml
